[package]
name = "gemstone-js-native"
version = "0.1.0-alpha.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
gemstone-gci = { path = "../gemstone-rs/crates/gemstone-gci" }
napi = { version = "2", default-features = false, features = ["napi8"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
