/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LoginOptions {
  username: string
  password: string
  flags?: number
  haltOnError?: boolean
}
export interface GciErrorInfo {
  number: number
  fatal: boolean
  message: string
  reason?: string
  category: string
  context: string
  exceptionObj: string
  args: Array<string>
}
export interface GemStoneNativeError extends Error {
  code: 'GEMSTONE_GCI_ERROR'
  operation: string
  nativeCode?: string
  gciNumber?: number
  fatal?: boolean
  gciMessage?: string
  reason?: string
  category?: string
  context?: string
  exceptionObj?: string
  args?: Array<string>
  info?: GciErrorInfo
}
export declare function isGemStoneNativeError(error: unknown): error is GemStoneNativeError
export interface SymDictLookup {
  value: string
  assoc: string
}
export declare class GciSessionWorker {
  constructor(libPath?: string | undefined | null)
  call(method: string, args?: Array<unknown>): Promise<unknown>
  close(): Promise<void>
  [Symbol.asyncDispose](): Promise<void>
  init(libPath?: string | undefined | null): Promise<number>
  libraryPath(): Promise<string>
  encrypt(password: string): Promise<string>
  setNet(stoneName: string, hostUsername: string, encryptedHostPassword: string, gemService: string): Promise<void>
  loginEx(options: LoginOptions): Promise<number>
  logout(): Promise<number>
  commit(): Promise<boolean>
  abort(): Promise<boolean>
  err(): Promise<GciErrorInfo | null>
  executeStr(source: string, receiver?: string | undefined | null): Promise<string>
  perform(receiver: string, selector: string, args?: Array<string> | undefined | null): Promise<string>
  newString(value: string): Promise<string>
  newSymbol(value: string): Promise<string>
  newOop(classOop: string): Promise<string>
  resolveSymbol(name: string, symbolList?: string | undefined | null): Promise<string>
  fetchClass(oop: string): Promise<string>
  fetchSize(oop: string): Promise<number>
  fetchBytes(oop: string, start: number, count: number): Promise<Uint8Array>
  getSessionId(): Promise<number>
  setSessionId(sessionId: number): Promise<void>
  needsCommit(): Promise<boolean>
  inTransaction(): Promise<boolean>
  fltToOop(value: number): Promise<string>
  oopToFlt(oop: string): Promise<number>
  symDictAt(dict: string, key: string): Promise<SymDictLookup>
  symDictAtPut(dict: string, key: string, value: string): Promise<void>
  symDictAtObjPut(dict: string, key: string, value: string): Promise<void>
  strKeyValueDictAt(dict: string, key: string): Promise<string>
  strKeyValueDictAtPut(dict: string, key: string, value: string): Promise<void>
  addOopToExportSet(oop: string): Promise<void>
  removeOopFromExportSet(oop: string): Promise<void>
}
export declare function createGciSessionWorker(libPath?: string | undefined | null): GciSessionWorker
export declare function smallintToOop(value: number): string
export declare function oopToSmallint(value: string): number
export declare function isSmallintOop(value: string): boolean
export declare function boolToOop(value: boolean): string
export declare function charToOopString(value: string): string
export declare function oopToCharString(value: string): string | null
export declare class Gci {
  constructor(libPath?: string | undefined | null)
  init(libPath?: string | undefined | null): number
  libraryPath(): string
  encrypt(password: string): string
  setNet(stoneName: string, hostUsername: string, encryptedHostPassword: string, gemService: string): void
  loginEx(options: LoginOptions): number
  logout(): number
  commit(): boolean
  abort(): boolean
  err(): GciErrorInfo | null
  executeStr(source: string, receiver?: string | undefined | null): string
  perform(receiver: string, selector: string, args?: Array<string> | undefined | null): string
  newString(value: string): string
  newSymbol(value: string): string
  newOop(classOop: string): string
  resolveSymbol(name: string, symbolList?: string | undefined | null): string
  fetchClass(oop: string): string
  fetchSize(oop: string): number
  fetchBytes(oop: string, start: number, count: number): Uint8Array
  getSessionId(): number
  setSessionId(sessionId: number): void
  needsCommit(): boolean
  inTransaction(): boolean
  fltToOop(value: number): string
  oopToFlt(oop: string): number
  symDictAt(dict: string, key: string): SymDictLookup
  symDictAtPut(dict: string, key: string, value: string): void
  symDictAtObjPut(dict: string, key: string, value: string): void
  strKeyValueDictAt(dict: string, key: string): string
  strKeyValueDictAtPut(dict: string, key: string, value: string): void
  addOopToExportSet(oop: string): void
  removeOopFromExportSet(oop: string): void
}
