/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LoginOptions {
  username: string
  password: string
  flags?: number
  haltOnError?: boolean
}
export interface GciErrorInfo {
  number: number
  fatal: boolean
  message: string
  reason?: string
}
export interface GemStoneNativeError extends Error {
  code: 'GEMSTONE_GCI_ERROR'
  operation: string
  nativeCode?: string
  gciNumber?: number
  fatal?: boolean
  gciMessage?: string
  reason?: string
  info?: GciErrorInfo
}
export interface SymDictLookup {
  value: string
  assoc: string
}
export declare function smallintToOop(value: number): string
export declare function oopToSmallint(value: string): number
export declare function isSmallintOop(value: string): boolean
export declare function boolToOop(value: boolean): string
export declare function charToOopString(value: string): string
export declare function oopToCharString(value: string): string | null
export class Gci {
  constructor(libPath?: string | undefined | null)
  init(libPath?: string | undefined | null): number
  libraryPath(): string
  encrypt(password: string): string
  setNet(stoneName: string, hostUsername: string, encryptedHostPassword: string, gemService: string): void
  loginEx(options: LoginOptions): number
  logout(): number
  commit(): boolean
  abort(): boolean
  err(): GciErrorInfo | null
  executeStr(source: string, receiver?: string | undefined | null): string
  perform(receiver: string, selector: string, args?: Array<string> | undefined | null): string
  newString(value: string): string
  newSymbol(value: string): string
  newOop(classOop: string): string
  resolveSymbol(name: string, symbolList?: string | undefined | null): string
  fetchClass(oop: string): string
  fetchSize(oop: string): number
  fetchBytes(oop: string, start: number, count: number): Buffer
  getSessionId(): number
  setSessionId(sessionId: number): void
  needsCommit(): boolean
  inTransaction(): boolean
  fltToOop(value: number): string
  oopToFlt(oop: string): number
  symDictAt(dict: string, key: string): SymDictLookup
  symDictAtPut(dict: string, key: string, value: string): void
  symDictAtObjPut(dict: string, key: string, value: string): void
  strKeyValueDictAt(dict: string, key: string): string
  strKeyValueDictAtPut(dict: string, key: string, value: string): void
  addOopToExportSet(oop: string): void
  removeOopFromExportSet(oop: string): void
}
